# Generated by Django 5.1.4 on 2025-04-26 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brakerotor',
            name='actuation',
        ),
        migrations.AddField(
            model_name='brakerotor',
            name='pads_compatibility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.brakepadscompound', verbose_name='Brake pads compound compatibility'),
        ),
        migrations.CreateModel(
            name='MTBBicycleConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Weight (kg)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price (€)')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='bicycles/', verbose_name='Bicycle Image')),
                ('name', models.CharField(max_length=25, verbose_name='Bicycle configuration name')),
                ('bottom_bracket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.bottombracket', verbose_name='Bottom Bracket')),
                ('brake', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.brakes', verbose_name='Brake')),
                ('cassette', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.cassette', verbose_name='Cassette')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.chain', verbose_name='Chain')),
                ('crankset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.crankset', verbose_name='Crankset')),
                ('derailleur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.derailleur', verbose_name='Rear Derailleur')),
                ('fork', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.fork', verbose_name='Fork')),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.frame', verbose_name='Frame')),
                ('front_derailleur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.frontderailleur', verbose_name='Front Derailleur')),
                ('front_rotor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='front_rotor_configurations', to='webapp.brakerotor', verbose_name='Front Rotor')),
                ('front_shifter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rear_shifter_configurations', to='webapp.shifter', verbose_name='Front Shifter')),
                ('rear_rotor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rear_rotor_configurations', to='webapp.brakerotor', verbose_name='Rear Rotor')),
                ('rear_shifter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='front_shifter_configurations', to='webapp.shifter', verbose_name='Rear Shifter')),
                ('wheelset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.wheelset', verbose_name='Wheel Set')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
