# Generated by Django 5.1.4 on 2025-06-15 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteererType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Steerer Tube Type')),
            ],
        ),
        migrations.AddField(
            model_name='frame',
            name='chainline',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Chainline (mm)'),
        ),
        migrations.AddField(
            model_name='frontwheel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='components/wheels/', verbose_name='Wheel Image'),
        ),
        migrations.AddField(
            model_name='rearwheel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='components/wheels/', verbose_name='Wheel Image'),
        ),
        migrations.AddField(
            model_name='wheelset',
            name='wheelset_image',
            field=models.ImageField(blank=True, null=True, upload_to='components/wheelsets/', verbose_name='WheelSet Image'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='rs_size_length',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rear Shock Size Eye-to-Eye in mm'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='rs_stroke',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Rear Shock Stroke in mm'),
        ),
        migrations.AddField(
            model_name='fork',
            name='steerer_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='webapp.steerertype', verbose_name='Steerer Tube Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frame',
            name='steerer_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='webapp.steerertype', verbose_name='Steerer Tube Type'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(db_index=True, max_length=100, verbose_name='Series Name')),
                ('features', models.TextField(blank=True, null=True, verbose_name='Features')),
                ('technology', models.TextField(blank=True, null=True, verbose_name='Technology')),
                ('color', models.CharField(db_index=True, max_length=50, verbose_name='Color')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Weight (kg)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price (€)')),
                ('manufacturer_num', models.CharField(db_index=True, max_length=15, verbose_name='Manufacturer number')),
                ('tubeless_ready', models.BooleanField(default=False, verbose_name='Tubeless Ready')),
                ('image', models.ImageField(blank=True, null=True, upload_to='components/tyres/', verbose_name='Tyre Image')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.application', verbose_name='Application')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.brand', verbose_name='Brand name')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.material', verbose_name='Material')),
                ('tyre_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.tyresize', verbose_name='Tyre Width')),
                ('wheel_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.wheelsize', verbose_name='Wheel Size')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
